oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/callback/google}
    playground-client-id: ${GOOGLE_PLAYGROUND_CLIENT_ID}
    
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}